name: build
on:
  workflow_dispatch:
  push:
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0

      - name: Install Ninja
        run: sudo apt install ninja-build

      - name: Configure CMake
        run: cmake . -B build -G Ninja

      - name: Build targets
        run: cmake --build build

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0

      - name: Install Ninja
        run: sudo apt install ninja-build

      - name: Configure CMake
        run: cmake . -B build -G Ninja -D BUILD_TESTING=ON

      - name: Build targets
        run: cmake --build build

      - name: Run tests
        run: ctest --verbose --test-dir build --no-compress-output -T Test || true

      - name: Download Testspace client
        run: curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | tar -zxvf- -C build

      - name: Configure Testspace client
        working-directory: build
        run: |
          ./testspace config url ${{ secrets.TESTSPACE_URL }}
          ./testspace config project ${{ secrets.TESTSPACE_PROJECT }}
          ./testspace config space ${{ github.ref_name }}

      - name: Send test result to Testspace
        working-directory: build
        run: ./testspace [Tests]"Testing/*/Test.xml"

      - name: Install lcov
        run: sudo apt install lcov

      - name: Generate code coverage info
        run: |
          lcov --directory . --capture --no-external --output-file build/coverage.info
          lcov --remove build/coverage.info "*/build/*" --output-file build/coverage.info

      - name: Send code coverage info to Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          path-to-lcov: build/coverage.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
