name: build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0

      - name: Install LLVM and Ninja
        run: sudo apt install llvm ninja-build

      - name: Configure CMake
        run: cmake . -B build -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -G Ninja

      - name: Build targets
        run: cmake --build build

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0

      - name: Install LLVM and Ninja
        run: sudo apt install llvm ninja-build

      - name: Configure CMake
        run: cmake . -B build -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -G Ninja -DBUILD_TESTING=ON

      - name: Check for code formatting
        run: |
          cmake --build build --target format
          cmake --build build --target check-format

      - name: Build targets
        run: cmake --build build

      - name: Run tests
        run: ctest --verbose --test-dir build

      - name: Install gcovr
        run: pip3 install gcovr

      - name: Generate code coverage info
        working-directory: build
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: gcovr -r .. --gcov-executable 'llvm-cov gcov' --exclude-directories _deps -e _deps --coveralls coverage.json

      - name: Send code coverage info to Coveralls
        working-directory: build
        run: curl -v -F json_file=@coverage.json https://coveralls.io/api/v1/jobs
